"""document table

Revision ID: 1d2bdc863cee
Revises: 77604e523e59
Create Date: 2026-07-18 09:28:07.603973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2bdc863cee'
down_revision: Union[str, Sequence[str], None] = '77604e523e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('UserId', sa.String(length=50), nullable=False),
    sa.Column('OriginalFileName', sa.String(length=100), nullable=False),
    sa.Column('StoragePath', sa.String(length=200), nullable=False),
    sa.Column('MimeType', sa.String(length=50), nullable=False),
    sa.Column('FileSize', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Document')
    # ### end Alembic commands ###
