"""table for storing chunks


Revision ID: 3f4be29b7dbc
Revises: 1d2bdc863cee
Create Date: 2026-07-18 16:58:46.714188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4be29b7dbc'
down_revision: Union[str, Sequence[str], None] = '1d2bdc863cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentChunks',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('DocumentId', sa.String(length=50), nullable=False),
    sa.Column('PageNumber', sa.Integer(), nullable=False),
    sa.Column('ChunkNumber', sa.Integer(), nullable=False),
    sa.Column('ChunkText', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentChunks')
    # ### end Alembic commands ###
