"""added embeddings column

Revision ID: 4389a7c8ceda
Revises: 3f4be29b7dbc
Create Date: 2026-07-19 14:38:42.715931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '4389a7c8ceda'
down_revision: Union[str, Sequence[str], None] = '3f4be29b7dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentChunks', sa.Column('Embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DocumentChunks', 'Embedding')
    # ### end Alembic commands ###
