"""table for storing client message

Revision ID: 6aeb447f725e
Revises: 4389a7c8ceda
Create Date: 2026-07-19 18:36:25.871706

"""
from typing import Sequence, Union

from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aeb447f725e'
down_revision: Union[str, Sequence[str], None] = '4389a7c8ceda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientMessages',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('DocId', sa.String(length=50), nullable=False),
    sa.Column('Message', sa.String(), nullable=False),
    sa.Column('Embeddings', Vector(384), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientMessages')
    # ### end Alembic commands ###
