"""your_migration_message

Revision ID: 9a8c895fc39d
Revises: d99436e61a92
Create Date: 2026-07-21 16:20:36.018032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8c895fc39d'
down_revision: Union[str, Sequence[str], None] = 'd99436e61a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConversationalMessages', sa.Column('CreatedAt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ConversationalMessages', 'CreatedAt')
    # ### end Alembic commands ###
