"""added usedid in table of DocumentChunks

Revision ID: c6354a8627b5
Revises: d963b40587b0
Create Date: 2026-07-19 23:01:17.968194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6354a8627b5'
down_revision: Union[str, Sequence[str], None] = 'd963b40587b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentChunks', sa.Column('UserId', sa.String(length=50), nullable=True)) # Modified manually to set nullable=True
    op.alter_column('DocumentChunks', 'DocumentId',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DocumentChunks', 'DocumentId',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('DocumentChunks', 'UserId')
    # ### end Alembic commands ###
