"""table for storing client message

Revision ID: d963b40587b0
Revises: 6aeb447f725e
Create Date: 2026-07-19 21:25:36.695501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd963b40587b0'
down_revision: Union[str, Sequence[str], None] = '6aeb447f725e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientMessages', sa.Column('UserId', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientMessages', 'UserId')
    # ### end Alembic commands ###
