"""added conversation message table

Revision ID: d99436e61a92
Revises: c6354a8627b5
Create Date: 2026-07-21 08:18:34.452024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99436e61a92'
down_revision: Union[str, Sequence[str], None] = 'c6354a8627b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConversationalMessages',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('DocId', sa.String(length=50), nullable=False),
    sa.Column('UserId', sa.String(length=50), nullable=False),
    sa.Column('Message', sa.String(), nullable=False),
    sa.Column('Response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ConversationalMessages')
    # ### end Alembic commands ###
