"""removed nullable password

Revision ID: fbcbb72373e5
Revises: b9b64c7d2e9b
Create Date: 2026-07-16 18:17:26.207590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcbb72373e5'
down_revision: Union[str, Sequence[str], None] = 'b9b64c7d2e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'Password')
    # ### end Alembic commands ###
